name: wowsell
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #Dependencies to be added
  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.9.1
  simple_animations: ^1.3.3
  fluttertoast: ^8.0.7
  sqflite: ^2.0.0+3
  path_provider: ^2.0.2
  rflutter_alert: ^2.0.2
  provider: ^5.0.0
  shared_preferences: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/Wowsell_Icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
  fonts:
    - family: Satisfy
      fonts:
        - asset: assets/fonts/Satisfy-Regular.ttf